refactor: improve management of rules for pipelines

diff --git a/staging/.gitlab-ci.yml b/staging/.gitlab-ci.yml
--- a/staging/.gitlab-ci.yml
+++ b/staging/.gitlab-ci.yml
@@ -64,12 +64,14 @@ build:
       docker push $REGISTRY_IMAGE_BASE_PATH/$service:latest;
       docker push $REGISTRY_IMAGE_BASE_PATH/$service:$VERSION;
       done
+  rules:       
+    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
 
 deploy:
   stage: staging
   image: mcr.microsoft.com/azure-cli
-  rules:
-    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
+  rules:       
+    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
   script:
     - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
     - az webapp config container set --name $AZURE_WEBAPP_NAME --resource-group $AZURE_WEBAPP_RESOURCE_GROUP --multicontainer-config-type compose --multicontainer-config-file docker-compose.deploy.yml --container-registry-user $PULL_IMAGE_TOKEN_USERNAME --container-registry-password $PULL_IMAGE_TOKEN_PASSWORD
@@ -84,12 +86,16 @@ deploy:
         echo "Azure Web App is not ready yet. Waiting for 10 seconds..."
         sleep 10
       done
+      if [ "$HTTP_STATUS" -ne 200 ]; then
+        echo "Azure Web App failed to become functional."
+        exit 1
+      fi
 
 e2e tests:
   stage: e2e
   image: mcr.microsoft.com/playwright:v1.50.1-jammy
-  rules:
-    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
+  rules:       
+    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
   script:
     - cd ./e2e
     - npm ci
